### ISSUE TITLE
Change Expense Status

### ISSUE THREAD

**Issue by kil-jonluc** [kil-jonluc/ExpenseTracker#22]
Add drop down to change the status of the expense. 

Then have conditions required for each status.
-Under Review - not conditions for status change
-Approved - needs amount refunded to be entered. Optional: have a radio button that when clicked enters the full amount in the input box. 
-Open back to user - requires the some note to be sent to the user. 
-Denied - Optional note to user.

When the required conditions are met then the employer can change the status of the expense.

Maybe we can have a remove expense button.

**Comment by townsendtechllc** [comment]
Build out infrastructure for seeing and editing status
