### ISSUE TITLE
Figure out how Database Project and MVC project relate

### ISSUE THREAD

**Issue by kil-jonluc** [kil-jonluc/ExpenseTracker#5]
ExpenseProjectDBSchema and Expense Tracker are two different Repositories and though task related they are on two different repos. Don't know how to put that together the best way?

**Comment by townsendtechllc** [comment]
It'll depend on what's in each one. Let's discuss this while looking at the code

**Comment by townsendtechllc** [comment]
Let's discuss this while looking at the code. This and issue #4 should probably sorted out first.
