### ISSUE TITLE
List Expenses View

### ISSUE THREAD

**Issue by kil-jonluc** [kil-jonluc/ExpenseTracker#9]
Make a list of the the expenses connected to the logged in user.

**Comment by kil-jonluc** [comment]
Have a status column with one of the following 
1. Submitted - meaning that the user cannot edit it without it being released back to the user from the employer
2. Under Review - The employer is looking at it
3. Approved - Employer approved and the user should be getting paid
4. Open to edit - status that the expenses it is in until it gets submitted to the Employer

https://github.com/kil-jonluc/ExpenseProjectDBSchema/issues/5#issue-619343463

**Comment by townsendtechllc** [comment]
Basic view is implemented, once we add the expense "Status" to the DB we can add the specified fields above

**Comment by kil-jonluc** [comment]
Have it set to under review when created.
Have it locked out to edit for employee unless status changed by employer of company.  So only available to edit if "with employee"
